"""empty message

Revision ID: 94d77c043aad
Revises: d7c7930d04b2
Create Date: 2023-08-31 19:19:31.569487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d77c043aad'
down_revision = 'd7c7930d04b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=120), nullable=False),
    sa.Column('Height', sa.String(length=80), nullable=False),
    sa.Column('Mass', sa.String(length=80), nullable=False),
    sa.Column('Hair_Color', sa.String(length=80), nullable=False),
    sa.Column('Skin_Color', sa.String(length=80), nullable=False),
    sa.Column('Eye_Color', sa.String(length=80), nullable=False),
    sa.Column('Birth_Year', sa.String(length=80), nullable=False),
    sa.Column('Gender', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=120), nullable=False),
    sa.Column('Director', sa.String(length=80), nullable=False),
    sa.Column('Produccion', sa.String(length=80), nullable=False),
    sa.Column('Fecha_de_Estreno', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Title')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.String(length=80), nullable=False),
    sa.Column('rotation_period', sa.String(length=80), nullable=False),
    sa.Column('orbital_period', sa.String(length=80), nullable=False),
    sa.Column('gravity', sa.String(length=80), nullable=False),
    sa.Column('population', sa.String(length=80), nullable=False),
    sa.Column('climate', sa.String(length=80), nullable=False),
    sa.Column('terrain', sa.String(length=80), nullable=False),
    sa.Column('surface_water', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Modelo', sa.String(length=120), nullable=False),
    sa.Column('Manufacturer', sa.String(length=80), nullable=False),
    sa.Column('Cost_in_credits', sa.String(length=80), nullable=False),
    sa.Column('Lenght', sa.String(length=80), nullable=False),
    sa.Column('Max_Speed', sa.String(length=80), nullable=False),
    sa.Column('Crew', sa.String(length=80), nullable=False),
    sa.Column('Passengers', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Modelo')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('vehicle')
    op.drop_table('planets')
    op.drop_table('films')
    op.drop_table('characters')
    # ### end Alembic commands ###
